### ISSUE TITLE
[RFE] stop running tests on test failure?

### ISSUE THREAD

**Issue by thoraxe** [tlevine/urchin#16]
I don't see any option/flag to make Urchin stop running tests if a test fails.

I'm actually trying to use Urchin as a setup framework for a piece of software. Rather than wrap every setup item in some weird bash block, Urchin seemed like a good fit, except for this one piece.

**Comment by tlevine** [comment]
How interesting! I would love to learn more of how Urchin could work
as a setup framework.

Implementing this would be straightforward, but there is no such flag at
the moment. Urchin discovers files recursively in directories, so I
think we would return something other than zero from the recursive
function when something fails and then propogate non-zero returns.

I'll explain further as to how to do this if you are interested in
writing it yourself; otherwise, you can wait until I or someone else
maybe writes it.

**Comment by thoraxe** [comment]
Thanks for the feedback. Here's an example of what I'm doing, kinda sorta:

https://github.com/thoraxe/training/blob/training-setup/setup-training.sh

This is a really ugly hack-job somewhat inspired by Urchin. I would have loved to have each function be a script that was automatically run. Basically I'm just executing the functions until one of them fails. If it fails, we exit immediately and do not continue.

My bash-fu is not good enough to try to hack at it myself, otherwise I would gladly submit a PR.

**Comment by tlevine** [comment]
Oh neat. We could add a flag that completely disables test reporting
(because I don't think you care about that) and just runs all of the
files. Did I get that right?

**Comment by thoraxe** [comment]
I mean, the reporting would be nice, but it's not necessarily required.

I just like the colored checks and xs :)

**Comment by tlevine** [comment]
This is part of Urchin now.
